### ISSUE TITLE
what does gid_tid do?

### ISSUE THREAD

**Issue by enshulv** [ccloli/e-hentai-db#20]
huge numbers stored in it,doesn't seem to be of much use...

**Comment by ccloli** [comment]
It's a mapping of gallery id and its related tags' ids. Though the tag id is auto-generated and not the E-Hentai provided one, and E-Hentai tweaked some tags recently, some tags are merged or duplicated.

**Comment by enshulv** [comment]
okey...that to say, deleting it doesn't affect any functions, right?

**Comment by ccloli** [comment]
If you don't care the tags of each gallery, then yes, though I think you DO care them.

**Comment by enshulv** [comment]
ok, thank you for reply.
