### ISSUE TITLE
Database dump refresh

### ISSUE THREAD

**Issue by marcandjulien** [ccloli/e-hentai-db#36]
I found the gdata.json from a few years back and your June 06 2022 database dump and they are very appreciated. Would it be possible to get a more recent database dump.

I'm writing a cli tool to add e-hentai metadata to my local book library and while I succeeded in web scraping the website search and using E-H API to get the metadata, the rate limiting is holding me back. Having a local metadata database would enable me to go much faster.

**Comment by ccloli** [comment]
See https://github.com/ccloli/e-hentai-db/releases/tag/database-dump-2023-03-04 .

Note that some critical shutdowns occured around the end of last year, so some data may not complete.
